### ISSUE TITLE
jsonValidate.py should return an non zero status code in case of validation error

### ISSUE THREAD

**Issue by xrobin** [inab/extended-json-schema-validators#3]
In order to automate the validation of the CAMEO benchmark data, I need an automated way to detect if the validation was successful or not.

I'm using the `python/jsonValidate.py`. Unfortunately the script always returns a status code 0 when there are validation errors (except if there's a JSON syntax error, where it returns status 1). This means that the only way to detect a validation error is to scan the output, as far as I can tell, which is inconvenient and error prone.

It would be nice if the script could return a non zero error code upon validation error.

### Steps to reproduce:

Generate an invalid JSON file:

    echo '{"_schema": "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Dataset"}' > invalid.json

Run the validator

    python extended-json-schema-validators/python/jsonValidate.py     benchmarking-data-model/json-schemas/1.0.x     inva
lid.json

### Observed result

The script returns 0

### Expected result

The script returns a value > 0

**Comment by jmfernandez** [comment]
Dear Xavier,
I apologize in advance, I have realized I left behind this issue you opened, related to the python implementation of the extended JSON validator.

As the development around this validator was spread through forks over several repositories, I was working in October on the reunification of all the improvements in a common place (https://github.com/inab/python-extended-json-schema-validator/), and publishing the developments in PyPI (https://pypi.org/project/extended-json-schema-validator/).

I have read the issue you describe, and it is fixed in current "reunified" development. The script exit code is 2 when there is at least one error. Also, you can now save a JSON description of the errors to a report file.

Could you check whether this issue is fixed there, please?

**Comment by xrobin** [comment]
Yes I can confirmed it's fixed and works properly.
A pip installable package is a very neat idea, very appreciated!
